baseURL = 'http://morestuff.app/'
title = 'MoreStuff'
theme = 'gokarna'
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

pygmentsStyle = "monokai"

[params]
  avatarURL = "/images/morestuff_logo.webp"
  avatarSize = "size-m"
  AvatarAltText = "avatar"

  footer = "MiddlePoint Solutions"
  description = "Get more stuff done!"

[menu]
  [[menu.main]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 1

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false